src/Entity/Roulette.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RouletteRepository")
 */
class Roulette
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $played_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $to_pay;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $amount;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Profil", mappedBy="roulette")
     */
    private $profils;

    public function __construct()
    {
        $this->profils = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlayedAt(): ?\DateTimeInterface
    {
        return $this->played_at;
    }

    public function setPlayedAt(?\DateTimeInterface $played_at): self
    {
        $this->played_at = $played_at;

        return $this;
    }

    public function getToPay(): ?int
    {
        return $this->to_pay;
    }

    public function setToPay(int $to_pay): self
    {
        $this->to_pay = $to_pay;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(?int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * @return Collection|Profil[]
     */
    public function getProfils(): Collection
    {
        return $this->profils;
    }

    public function addProfil(Profil $profil): self
    {
        if (!$this->profils->contains($profil)) {
            $this->profils[] = $profil;
            $profil->addRoulette($this);
        }

        return $this;
    }

    public function removeProfil(Profil $profil): self
    {
        if ($this->profils->contains($profil)) {
            $this->profils->removeElement($profil);
            $profil->removeRoulette($this);
        }

        return $this;
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Entity\BlackJack;
use App\Entity\Card;
use App\Form\AsType;
use App\Service\GameService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/game", name="game_")
 */
class GameController extends AbstractController
{

    const MAX_VALUE_TO_DRAW = 17;

    /**
     * @Route("", name="index")
     */
    public function index()
    {
        if ($this->getUser()) {
            return $this->render('game/index.html.twig', [
                'user' => $this->getUser()
            ]);
        } else {
            $this->addFlash('warning', 'Merci de vous connecter pour accéder à cet espace !');
            return $this->redirectToRoute('app_index');
        }
    }

    /**
     * @Route("/new", name="new")
     * @param EntityManagerInterface $entityManager
     * @return RedirectResponse
     * @throws \Exception
     */
    public function newGame(EntityManagerInterface $entityManager)
    {
        if ($this->getUser()->getProfil()->getTotalAmount() > 0) {
            $today = new \DateTime('now');
            $blackJack = new BlackJack();
            $blackJack->setPlayedAt($today);
            $blackJack->setAmount($this->getUser()->getProfil()->getTotalAmount());
            $blackJack->setToPay(0);
            $blackJack->setPlayerScore(0);
            $blackJack->setBankScore(0);

            $cards = $this->getDoctrine()
                ->getRepository(Card::class)
                ->findAll();

            foreach ($cards as $card) {
                $blackJack->addCard($card);
            }

            $entityManager->persist($blackJack);
            $entityManager->persist($this->getUser()->getProfil()->addBlackjack($blackJack));

            $entityManager->flush();
            return $this->redirectToRoute('game_choice', [
                'id' => $blackJack->getId(),
            ]);

        } else {
            $this->addFlash('warning', 'Vous n\'avez plus assez de WildCoins pour jouer.');
            return $this->redirectToRoute('game_index');
        }
    }

    /**
     * @Route("/choice/{id}", name="choice")
     * @param BlackJack $blackJack
     * @return Response
     */
    public function choiceAction(BlackJack $blackJack)
    {
        return $this->render('game/choice.html.twig', [
            'user'      => $this->getUser(),
            'blackJack' => $blackJack,
        ]);
    }

    /**
     * @Route("/draw/{id}", name="draw")
     * @param BlackJack $blackJack
     * @param GameService $gameService
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function Draw(BlackJack $blackJack, GameService $gameService, EntityManagerInterface $entityManager)
    {
        $drawCards   = $gameService->drawCards($blackJack->getCards());
        $playerCard  = $drawCards['player'];
        $playerScore = $gameService->scoreCard($playerCard->getValue());
        $bankCard    = '';

        if (($blackJack->getBankScore() < $blackJack->getPlayerScore()) || ($blackJack->getBankScore() < self::MAX_VALUE_TO_DRAW)) {
            $bankCard    = $drawCards['bank'];
            $bankScore   = $gameService->scoreCard($bankCard->getValue());

        } else {
            $bankScore = 0;
        }

        if ($playerScore === '') {
            if ($bankScore === '') {
                $bankScore = $gameService->makeChoice($blackJack->getBankScore());
            }
            $blackJack->setBankScore($blackJack->getBankScore() + $bankScore);
            $entityManager->flush();

            return $this->redirectToRoute('game_choice_value', [
                'id' => $blackJack->getId(),
            ]);
        }

        if ($bankScore === '') {
            $bankScore = $gameService->makeChoice($blackJack->getBankScore());
        }

        $blackJack->setPlayerScore($blackJack->getPlayerScore() + $playerScore);
        $blackJack->setBankScore($blackJack->getBankScore() + $bankScore);

        $entityManager->flush();

        if ($gameService->isLoser($blackJack->getPlayerScore())) {
            return $this->redirectToRoute('game_loser', [
                'id' => $blackJack->getId(),
            ]);
        } elseif ($gameService->isLoser($blackJack->getBankScore())) {
            return $this->redirectToRoute('game_winner', [
                'id' => $blackJack->getId(),
            ]);
        }

        return $this->render('game/drawResult.html.twig', [
            'user'        => $this->getUser(),
            'blackJack'   => $blackJack,
            'playerCard'  => $playerCard,
            'bankCard'    => $bankCard,
        ]);
    }

    /**
     * @Route("/choice-value/{id}", name="choice_value")
     * @param BlackJack $blackJack
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function choiceValue(BlackJack $blackJack, Request $request, EntityManagerInterface $entityManager)
    {
        $form = $this->createForm(AsType::class);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $selectedValue = $form->getData()['choice'];
            $blackJack->setPlayerScore($blackJack->getPlayerScore() + $selectedValue);

            $entityManager->flush();
            return $this->redirectToRoute('game_choice', [
                'id' => $blackJack->getId(),
            ]);
        }

        return $this->render('game/as.html.twig', [
            'id'        => $blackJack->getId(),
            'user'      => $this->getUser(),
            'blackJack' => $blackJack,
            'form'      => $form->createView(),
        ]);
    }

    /**
     * @Route("/loser/{id}", name="loser")
     * @param BlackJack $blackJack
     * @param GameService $gameService
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function looser(BlackJack $blackJack, GameService $gameService, EntityManagerInterface $entityManager)
    {
        $blackJack->setToPay(
            $gameService->calculateCoins(
                $blackJack->getPlayerScore(),
                $blackJack->getBankScore()
            )
        );

        $this->getUser()->getProfil()->setTotalAmount(
            $this->getUser()->getProfil()->getTotalAmount() + $blackJack->getToPay()
        );

        $entityManager->flush();

        return $this->render('game/lose.html.twig', [
            'id'        => $blackJack->getId(),
            'user'      => $this->getUser(),
            'blackJack' => $blackJack,
        ]);
    }

    /**
     * @Route("/winner/{id}", name="winner")
     * @param BlackJack $blackJack
     * @param GameService $gameService
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function winner(BlackJack $blackJack, GameService $gameService, EntityManagerInterface $entityManager)
    {
        $blackJack->setToPay(
            $gameService->calculateCoins(
                $blackJack->getPlayerScore(),
                $blackJack->getBankScore()
            )
        );

        $this->getUser()->getProfil()->setTotalAmount(
            $this->getUser()->getProfil()->getTotalAmount() - $blackJack->getToPay()
        );

        $entityManager->flush();

        return $this->render('game/win.html.twig', [
            'id'        => $blackJack->getId(),
            'user'      => $this->getUser(),
            'blackJack' => $blackJack,
        ]);
    }

    /**
     * @Route("/result/{id}", name="result")
     * @param BlackJack $blackJack
     * @param GameService $gameService
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function result(BlackJack $blackJack, GameService $gameService, EntityManagerInterface $entityManager)
    {
        if ($blackJack->getBankScore() < $blackJack->getPlayerScore() && $blackJack->getBankScore() <21) {
            $drawCards   = $gameService->drawCards($blackJack->getCards());
            $bankCard    = $drawCards['bank'];
            $bankScore   = $gameService->scoreCard($bankCard->getValue());
            if ($bankScore === '') {
                $bankScore = $gameService->makeChoice($blackJack->getBankScore());
            }

            $blackJack->setBankScore($blackJack->getBankScore() + $bankScore);

            $entityManager->flush();
            return $this->redirectToRoute('game_result', [
                'id' => $blackJack->getId(),
            ]);
        }

        if ( ($gameService->isLoser($blackJack->getBankScore()) && $blackJack->getPlayerScore() <= 21) ||
            ( $blackJack->getBankScore() <= 21 && $blackJack->getPlayerScore() <= 21 && $blackJack->getPlayerScore() > $blackJack->getBankScore())) {
            return $this->redirectToRoute('game_winner', [
                'id' => $blackJack->getId(),
            ]);
        } else {
            return $this->redirectToRoute('game_loser', [
                'id' => $blackJack->getId(),
            ]);
        }
    }

    /**
     * @Route("/games", name="games")
     * @return Response
     */
    public function historique()
    {
        $profil = $this->getUser()->getProfil();

        return $this->render('game/games.html.twig', [
            'profil' => $profil,
        ]);
    }
}

templates/game/as.html.twig
{% extends 'base.html.twig' %}

{% block title %}Place au jeu{% endblock %}

{% block body %}
    <div class="game-container">
        <div class="container">
            {% include 'game/templates/header.html.twig' %}
            <div class="d-flex justify-content-between">
                <p>Votre Score : {{ blackJack.playerScore }}</p>
                <p>Score du Croupier : {{ blackJack.bankScore }}</p>
            </div>
            <div class="boardtable mb-5 d-flex flex-column align-items-center">
                <h1>Vous avez pioché un AS</h1>
                <p> Faites votre choix</p>
                <div class="d-flex justify-content-around">
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    <button class="btn main-btn">Valider</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/game/choice.html.twig
{% extends 'base.html.twig' %}

{% block title %}Place au jeu{% endblock %}

{% block body %}
    <div class="game-container">
        <div class="container">
            {% include 'game/templates/header.html.twig' %}
            {% if blackJack.playerScore > 0 %}
                <div class="d-flex justify-content-between">
                    <p>Votre Score : {{ blackJack.playerScore }}</p>
                    <p>Score du Croupier : {{ blackJack.bankScore }}</p>
                </div>
            {% endif %}
            <div class="boardtable mb-5 d-flex justify-content-around align-items-center">
                <a href="{{ path('game_draw', { 'id' : blackJack.id }) }}">
                    <button type="button" class="btn main-btn">
                        Piocher une carte
                    </button>
                </a>

                <a href="{{ path('game_result', { 'id' : blackJack.id }) }}">
                    <button type="button" class="btn main-btn m-5">
                        Ne plus piocher
                    </button>
                </a>

            </div>
        </div>
    </div>
{% endblock %}

templates/game/drawResult.html.twig
{% extends 'base.html.twig' %}

{% block title %}Place au jeu{% endblock %}

{% block body %}
    <div class="game-container">
        <div class="container">
            {% include 'game/templates/header.html.twig' %}
            <div class="d-flex justify-content-between">
                <p>Votre Score : {{ blackJack.playerScore }}</p>
                <p>Score du Croupier : {{ blackJack.bankScore }}</p>
            </div>
            <div class="boardtable mb-5 d-flex justify-content-around align-items-center">
                <div class="d-flex flex-column">
                    <h2>Votre Carte</h2>
                    <img src="/uploads/blackjack/{{ playerCard.image }}" alt="{{ playerCard.name }}">
                    <a href="{{ path('game_draw', { 'id' : blackJack.id }) }}">
                        <button type="button" class="btn main-btn m-5">
                            Piocher une carte
                        </button>
                    </a>
                </div>

                <div class="d-flex flex-column">
                    <h2>Carte de la banque</h2>
                    {% if bankCard %}
                    <img src="/uploads/blackjack/{{ bankCard.image }}" alt="{{ bankCard.name }}">
                    {% else %}
                    <p>Le croupier n'a pas pioché</p>
                    {% endif %}
                    <a href="{{ path('game_result', { 'id' : blackJack.id }) }}">
                        <button type="button" class="btn main-btn m-5">
                            Ne plus piocher
                        </button>
                    </a>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/game/games.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Parties{% endblock %}

{% block body %}
    <div class="admin-container">
        <div class="container text-center">
            <table class="table table-hover">
                <thead>
                <tr>
                    <td></td>
                    <td></td>
                    <td>Détail</td>
                    <td>Perte/Gain</td>
                    <td>Scores</td>
                    <td>Date</td>
                </tr>
                </thead>
                {% for game in profil.blackJack %}
                    <tr>
                        <td>#</td>
                        <td>{{ loop.index }}</td>
                        <td>
                            {% if ( game.playerScore > game.bankScore and game.playerScore <= 21 ) or (game.playerScore < game.bankScore and game.bankScore > 21)  %}
                                Victoire
                            {% else %}
                                Défaite
                            {% endif %}
                        </td>
                        <td>{{ game.toPay | abs }}</td>
                        <td>Joueur {{ game.playerScore }} / {{ game.bankScore }} Croupier</td>
                        <td>{{ game.playedAt | date('d/m/Y H:i') }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

templates/game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Place au jeu{% endblock %}

{% block body %}
<div class="game-container">
    <div class="container">
        {% include 'game/templates/header.html.twig' %}

        <div class="boardtable mb-5 d-flex justify-content-around align-items-center">
            <button type="button" class="btn main-btn" data-toggle="modal" data-target="#RulesModal">
                Règles du jeu
            </button>
            {% include 'game/rules.html.twig' %}
            <a href="{{ path('game_new') }}">
                <button type="button" class="btn main-btn">
                    Début de Partie
                </button>
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/game/lose.html.twig
{% extends 'base.html.twig' %}

{% block title %}Place au jeu{% endblock %}

{% block body %}
    <div class="game-container">
        <div class="container">
            {% include 'game/templates/header.html.twig' %}
            <div class="d-flex justify-content-between">
                <p>Votre Score : {{ blackJack.playerScore }}</p>
                <p>Score du Croupier : {{ blackJack.bankScore }}</p>
            </div>
            <div class="boardtable mb-5 d-flex flex-column align-items-center">
                <h1>Vous avez perdu {{ blackJack.toPay | abs }} WildCoins</h1>
                <div>
                    <a href="{{ path('game_new') }}">
                        <button class="btn main-btn">Rejouer</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/game/rules.html.twig
<div class="modal fade" id="RulesModal" tabindex="-1" role="dialog" aria-labelledby="RulesModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Règles du jeu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="text-justify">
                    Pour gagner une partie, vous devez battre le score du croupier.<br>
                    Si vous dépassez 21 points, vous perdez. De même en cas d'égalité avec le croupier.<br>
                    A la fin de la partie, votre taux de WildCoins évolue en fonction de votre delta de point avec le croupier.<br>
                    Bonne chance à vous.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn main-btn" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

templates/game/win.html.twig
{% extends 'base.html.twig' %}

{% block title %}Place au jeu{% endblock %}

{% block body %}
    <div class="game-container">
        <div class="container">
            {% include 'game/templates/header.html.twig' %}
            <div class="d-flex justify-content-between">
                <p>Votre Score : {{ blackJack.playerScore }}</p>
                <p>Score du Croupier : {{ blackJack.bankScore }}</p>
            </div>
            <div class="boardtable mb-5 d-flex flex-column align-items-center">
                <h1>Vous avez gagné {{ blackJack.toPay | abs }} WildCoins</h1>
                <div>
                    <a href="{{ path('game_new') }}">
                        <button class="btn main-btn">Rejouer</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}